"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 1500
add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$c\
$lua\
$python\
$rust\
$character"""

[character]
success_symbol = '[󱐋](bold green)'
error_symbol = '[󱐋](bold red)'
vimcmd_symbol = '[󱐋](bold purple)'

[directory]
style = 'bold blue'
truncation_length = 1
read_only = ''

[git_branch]
symbol = ' '
style = 'bold bright-black'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
stashed = "≡"
style = "purple"

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\) '
style = "bright-black"

[c]
symbol = ' '

[nodejs]
symbol = ' '

[python]
symbol = ' '

[lua]
symbol = ' '

[rust]
symbol = ' '
